# Generated by Django 2.1.3 on 2018-11-17 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('_end_date_old', models.DateField()),
                ('price', models.IntegerField(default=0)),
                ('installation_date', models.DateField()),
                ('removal_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Installation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiving_date', models.DateField()),
                ('price', models.IntegerField()),
                ('update', models.BooleanField()),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.Banner')),
            ],
        ),
    ]
