# Generated by Django 2.1.3 on 2018-11-17 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='_end_date_old',
        ),
    ]
